### ISSUE TITLE
Getting started guide not working

### ISSUE THREAD

**Issue by mwalk-dev** [crashkonijn/GOAP#10]
Hi, I just grabbed the new version and I'm following the [getting started guide](https://goap.crashkonijn.com/introduction/gettingstarted) using ScriptableObjects in Unity 2022.2.14f1. `GoapSet.ResolveGoal` is throwing a `KeyNotFoundException` when I enter play mode. From stepping through the code, it appears that `ClassResolver.Load` is discarding my action and goal because their `ClassType` property is an empty string. Is there an additional step I need to take?

**Comment by crashkonijn** [comment]
Hi @mwalk-dev !

Thanks for trying it out! 

On the scriptable object configs, did you select a class on all of them?

If you hit me up on [discord ](https://discord.gg/dCPnHaYNrm) I can help you faster.

**Comment by mwalk-dev** [comment]
Thanks for the quick response! You are correct, it was user error; I missed setting the class on my goal SO. I do think there's one other minor issue in the getting started guide - `WanderTargetSensor.GetRandomPosition` calls itself recursively. I changed that to just return the random position and now everything is working.

**Comment by crashkonijn** [comment]
I've updated the docs, but I'm having trouble updating the branch to master in GitBook. Having a look at it right now.

I also plan on creating a GOAP setup validator, which should help catching bugs like this.

Thanks for your help!

**Comment by crashkonijn** [comment]
Hi @mwalk-dev 

I wanted you to know I just released version 2.0.1 which includes GOAP set config validators!

They are run on play, and can be manually run from the set editors.
