### ISSUE TITLE
Question: How to implement local sensor for moving object?

### ISSUE THREAD

**Issue by NicholasDewberryOfficial** [crashkonijn/GOAP#107]
**Current behavior**
I have a "playerTargetSensor" script that takes the position of a player. I have an agent that walks up to the player and performs the desired action. 

A problem arises when the player moves around the scene. 

Lets say the player goes from position 1  to position 2. It starts at position 1 when it the scene begins, then goes to position 2 after a second. 

The agent moves to position 1 always, even if the player is moving towards position 2. I do not want this behavior because I don't want the agent to the past position, I want them to move to the current position. 

**Desired behavior**
If an agent is tracking a player, they should be able to see where the player is located, and simply move there. 

The sensor could have a function called "checkTargetPositionEvery3Seconds", and if the target position changes during those 3 seconds, it should be able to recalculate where to go. 

Due to performance concerns, we could also have the ability to have it based on a timer (so the position gets updated every 2 seconds rather than once a frame). 

**Work done to find a potential solution**

I've tried editing AgentMoveBehaviour to reset the ITarget if the player moves, but I haven't had much progress with that just yet. Still working on it. I think I'm going to look at the AgentBehaviour script and try to call the UpdateTarget() function. Right now, it looks like I kind of have to move around and modify either the AgentMoveBehaviour  or AgentBehaviour script. I'd prefer if it was possible to just edit the sensor for the player target instead of trying to manually reset the target. 

I've also tried asking the gitbooks AI, however it isn't really clear if they want me to edit the sensor file itself, or one of the agentbehaviour scripts.

**Comment by crashkonijn** [comment]
Hi there!

Thanks for trying out the package and reaching out! Could you please share your sensor?

**Comment by NicholasDewberryOfficial** [comment]
Here you go! : 

`using CrashKonijn.Goap.Classes;
using CrashKonijn.Goap.Interfaces;
using CrashKonijn.Goap.Sensors;
using UnityEngine;
using System.Collections;

public class PlayerTargetSensor : LocalTargetSensorBase
{
    
    GameObject pl = null; 
    // Called when the class is created.
    public override void Created()
    {
        if(pl == null){

         pl = GameObject.FindWithTag("Player");
        }
    }

    // Called each frame. This can be used to gather data from the world before the sense method is called.
    // This can be used to gather 'base data' that is the same for all agents, and otherwise would be performed multiple times during the Sense method.
    public override void Update()
    {
        if(pl.transform.hasChanged == true){
            pl = GameObject.FindWithTag("Player");  
        }
    }

    // Called when the sensor needs to sense a target for a specific agent.
    public override ITarget Sense(IMonoAgent agent, IComponentReference references)
    {
        var transformToChase = pl.transform.position;
        return new PositionTarget(transformToChase);
    }
}`

**Comment by crashkonijn** [comment]
Thanks for the reply!

You are looking for the `TransformTarget`, this stores the transform and returns the `transform.position`.

https://goap.crashkonijn.com/classes/sensors#targetsensor

**Comment by NicholasDewberryOfficial** [comment]
Thank you so much! This fixed my problem perfectly!
