### ISSUE TITLE
Question: Extending core classes like AgentEvents w.r.t package source

### ISSUE THREAD

**Issue by jzapdot** [crashkonijn/GOAP#122]
Hello, I'm reading through the docs and example code to understand how better this library would be built upon for a practical game example and came upon a good example of extension that fits several different core classes.

**Expected behavior**
In the docs for Events [here](https://goap.crashkonijn.com/classes/agentbehaviour#events) several example usages of `IAgentEvents` from an `AgentBehavior` can be found. `IAgentEvents` defines these four methods/events below:
```csharp
        event ActionDelegate OnActionStart;
        void ActionStart(IActionBase action);
        
        event ActionDelegate OnActionStop;
        void ActionStop(IActionBase action);
        
        event GoalDelegate OnGoalStart;
        void GoalStart(IGoalBase goal);
        
        event GoalDelegate OnNoActionFound;
        void NoActionFound(IGoalBase goal);
```

but in the sample code several other events are demonstrated which do not currently exist and would not be accessible from this interface without modifying it or overriding it in some fashion.

**From `EventExample`**
```csharp
this.agent.Events.OnNoActionFound += this.OnNoActionFound;
this.agent.Events.OnGoalCompleted += this.OnGoalCompleted;
```

**From `AgentMoveBehavior.cs`**
```csharp
this.agent.Events.OnTargetInRange += this.OnTargetInRange;
this.agent.Events.OnTargetChanged += this.OnTargetChanged;
this.agent.Events.OnTargetOutOfRange += this.OnTargetOutOfRange;
```

This would make sense for example code for a dev who was able to extend or define their own interfaces for these types (such as `IMyGameAgentEvents`), but much of this is not extendable or at least would require a fair amount of customization of the package source or recreating it outside of the package and type casting from the base interface. 

An example of this copying/duplication might be taking `AgentBehavior`, copying it into a new non-package class such as `MyGameAgentBehavior`, changing it to instantiate a `IMyGameAgentEvents` for `IAgentEvents`, and then wherever the extended events needed to be used casting the `Events` field to be `IMyGameAgentEvents`. 

This is all doable, but seems like it's working around a limitation of the base library's ability to be extended in this area. Alternatively I could download the package source locally to the repo, reference it locally, and directly modify the package code to game specific needs, but that would likely make taking future updates or fixes more difficult.

Though I used `AgentEvents` and `IAgentEvents` here specifically, there are several other areas with this kind of pattern that suffer from this extension problem. 

Are there other better ways to accomplish extending the capabilities of the GOAP library without modifying the package source or using workarounds as described above? Any other implementation approaches I should be considering?

**Unity Version**
**Unity 2022.3.11f1**

**Unity.Collections Version**
**v1.2.4**

**Package Version**
**v2.0.6**

**Additional context**
I appreciate the thought and effort that went into making this library and particularly that it seems relatively straightforward and stable.

**Comment by jzapdot** [comment]
> Hi there @jzapdot!
> 
> Thanks for having a go at the project and for your question!
> 
> The `IAgentEvents` interface does indeed not have these methods in v2.0.6, but they have been introduced since (latest version is 2.1.14).

Ah, that makes perfect sense hahaha. I thought I had recently pulled, but that must have been on a different machine.

> As for extendibility, this is indeed my intended purpose as much as possible although not everything is feasible. I am making good progress into increasing expandability for #120
> 
> As for the events specifically, they are meant as events that are produced by the GOAP system itself, what use-case would you have for extending it?

Ahh I see. I apologize, was confused with the difference between the older code I had and the sample code and had thought this was meant to be extended. I had seen the newer target-related events on the sample code and assumed those were project-specific extensions. I'll go through the newer source pulled from latest and re-evaluate what I was thinking.

> PS. I saw on your profile that it appears you're working for an game company. My dream for this project is that it get's used by professionals and actually drives the AI for games that have been released. If there's more limitations that would prevent you from doing so, please don't hesitate to get in contact and let me know :) (Either here or on Discord)

Happy to hop on discord and chat further! I often look to open source projects to see what might be good fits for our work or see what capabilities a developer(s) might approach a particular problem. I'm looking at GOAP for some side-project fun at the moment, but there have been several times I've advocated for using an open source tool for one project or another that I had familiarized myself with on side projects.

Feel free tro close this issue for now, I'll follow up with more up-to-date questions from the latest source.

**Comment by crashkonijn** [comment]
Don't forget to update the url in the package manager to include the specific version, otherwise the version you have depends on when you pull/add it to the project! This is something that wasn't in the docs back then.

```
https://github.com/crashkonijn/GOAP.git?path=/Package#2.1.14
```

Don't hesitate to ask if you have any further questions!
