### ISSUE TITLE
Bug: DebugGraph is a static object

### ISSUE THREAD

**Issue by mitsh** [crashkonijn/GOAP#126]
**Describe the bug**
I've installed the latest version of the package and gave me this error.

```
[Error] [17:00:15] [None] [Compiler] Cannot create an instance of the static class 'DebugGraph'
```

**Steps to Reproduce**
1. Install packages

**Expected behavior**
It should work normally.

**Screenshots**
![image](https://github.com/crashkonijn/GOAP/assets/895798/090cc3ef-0684-4f1d-89ac-374a00a152b6)

**Unity Version**
2023.2.2

**Unity.Collections Version**
2.2.1

**Package Version**
2.1.15

**Additional context**
It might conflict with this package https://assetstore.unity.com/packages/p/squiggle-21970, it has Class named DebugGraph.

**Comment by mitsh** [comment]
Yes. it worked well with absolute path class name.
```cs
var debugGraph = new CrashKonijn.Goap.Editor.Classes.DebugGraph(graph).GetGraph(graphRootNode);
```

**Comment by crashkonijn** [comment]
Thanks for you quick answer!

Technically the problem is Squiggle not using a namespace. Are you willing to create a PR for this fix?

**Comment by mitsh** [comment]
Sure I can do that. Is it okay to fix like that giving absolute class path?

**Comment by crashkonijn** [comment]
Yes that would be the fix! Please add a comment above it describing why there is an absolute reference.

Thanks in advance!

**Comment by crashkonijn** [comment]
2.1.16 has been released!

Thanks for becoming a contributor!

https://github.com/crashkonijn/GOAP/releases/tag/2.1.16
