### ISSUE TITLE
Question: How to know if the Goal was achieved?

### ISSUE THREAD

**Issue by hellobody** [crashkonijn/GOAP#135]
Hello,

First of all, thank you for the great framework!

I am currently learning how to use it, and I have a question: Are there any events within the "Goal" class that we could listen to in order to be notified when the goal is achieved?

We have some events/callbacks in the "Action" class, such as Start and End, so we can determine when an action starts or ends. It would be great to have something similar for the "Goal" class, like an Achieved event/callback.

Thanks.

**Comment by crashkonijn** [comment]
Hi!

Thank you for trying out the project and for reaching out!

No, at present there's no such callbacks. In general a goal is a desired world state, and actions already mutate the world state to reach that goal. That should mean that there's no requirement for changing anything in the goal.

The agent does contain the [OnGoalCompleted](https://github.com/crashkonijn/GOAP/blob/master/Package/Runtime/CrashKonijn.Goap/Behaviours/AgentEvents.cs#L33) event, which could be used to set a new goal.

If this is not enough, could you please give me an example of your use case to help me understand why this should be added?

Thanks in advance!

**Comment by hellobody** [comment]
Oh, thanks for the quick reply. Got you.
I think OnGoalCompleted is gonna be enough to detect goal completion event.
Thanks.
