### ISSUE TITLE
Question: What happens if at some point the planner didn't find any available action?

### ISSUE THREAD

**Issue by hellobody** [crashkonijn/GOAP#136]
Hi Peter.

Could you please help me to figure out the following?:

At some moment it may happen that an agent stucks with **NoAction** state.
Despite he still has an **active goal** and a moment later the world states change so, there are available actions appear again.

![image](https://github.com/crashkonijn/GOAP/assets/1161879/c463374f-2150-4932-954f-55dd7441e9d7)

But for some reason the planner no longer tries to find an available action for an agent to achieve the goal.
It doesn't check sensors anymore.

**What happens if at some point in time there is no available actions for the agent?**

- Does the planner stop trying to check if there any available actions?
- If yes then how to force the planner to look for available actions again?
- Should I clear and set the goal again?
- Or should I probably always have some fallback "idle" action without any conditions so the planner would always have some available action to pick up?

Thank you.

**Comment by hellobody** [comment]
Looks like I found related topic:
https://github.com/crashkonijn/GOAP/issues/51#issuecomment-1575500392

**Comment by hellobody** [comment]
Problem solved by adding **Idle** action with **no conditions** and **high cost**.
So it's chosen only in rare cases when no other actions available.

**Comment by crashkonijn** [comment]
Hi there Ivan!

Glad to see you've found the answer! I do believe that the best thing would indeed be to always have something to fall back to. You never know how your world state might end up :)

My assumption would be someone would set another goal when the even is thrown, and thus re-queueing. I do think it might be better to re-queue the agent when no action is found, as a backup. I will add a separate ticket for this.

Thanks for using the project and for reaching out!
