### ISSUE TITLE
Bug: In Node Viewer it's impossible to scroll the list of agents.

### ISSUE THREAD

**Issue by hellobody** [crashkonijn/GOAP#138]
**Describe the bug**
When there are many NPCs in the list in Node Viewer then it's impossible to scroll the list to see all the agents.

**Steps to Reproduce**
1. Add many agents (around 15 or more).
2. Run the game and open Node Viewer.
3. Try to scroll down the list of agents and try to select some agent in the bottom of the list.
4. Observe that the list is autoscrolling up every second and it's impossible to view or select all agents.

**Expected behavior**
The list of agents should be scrollable. It should be possible to see or select any agent from the list.

**Screenshots**
![image](https://github.com/crashkonijn/GOAP/assets/1161879/040b454a-17f8-4ff9-b3a7-cfdc10518fed)

**Unity Version**
2023.1.15f1.3067.8732

**Unity.Collections Version**
1.2.4

**Package Version**
2.1.16

**Comment by crashkonijn** [comment]
Hi @hellobody!

Thanks for your very descriptive bug report!

I hope I can look at this soon, I might have to rethink how the editor (or that part at least) works. The re-render is indeed what causes this issue.

**Comment by crashkonijn** [comment]
Should be fixed in https://github.com/crashkonijn/GOAP/releases/tag/2.1.17 !

**Comment by hellobody** [comment]
Thank you. Will test tomorrow.

**Comment by hellobody** [comment]
Works perfectly! Thank you.
