### ISSUE TITLE
Propose updating `InRange` to `StoppingDistance` for greater clarity

### ISSUE THREAD

**Issue by Layla-P** [crashkonijn/GOAP#165]
I find the name `InRange` or `OutOfRange` confusing for describing whether an agent is close enough to the target.

When I see `OutOfRange` on the debug, I think out of range exception.

I would prefer to see a systemic name change - here are some suggested locations:

1. [`SetInRange`](https://github.com/crashkonijn/GOAP/blob/92641cb26e5e6e93165da9f755dc05e31bca2ac4/Package/Runtime/CrashKonijn.Goap/Classes/Builders/ActionBuilder.cs#L46) changed to `SetStoppingDistance`
2. [`InRange`](https://github.com/crashkonijn/GOAP/blob/92641cb26e5e6e93165da9f755dc05e31bca2ac4/Package/Runtime/CrashKonijn.Goap/Configs/ActionConfig.cs#L13) changed to `StoppingDistance`
3. [`InRange `](https://github.com/crashkonijn/GOAP/blob/92641cb26e5e6e93165da9f755dc05e31bca2ac4/Package/Runtime/CrashKonijn.Goap/Scriptables/ActionConfigScriptable.cs#L23) changed to `StoppingDistance`
4. [`OutOfRange`](https://github.com/crashkonijn/GOAP/blob/92641cb26e5e6e93165da9f755dc05e31bca2ac4/Package/Runtime/CrashKonijn.Goap/Enums/AgentMoveState.cs#L7) changed to `NotInRange`

**Comment by crashkonijn** [comment]
I do like these changes!

What do you guys think about the [IsInRange](https://github.com/crashkonijn/GOAP/blob/master/Package/Runtime/CrashKonijn.Goap/Interfaces/IActionBase.cs#L14) method on an action, or the [TargetInRange and TargetOutOfRange](https://github.com/crashkonijn/GOAP/blob/master/Package/Runtime/CrashKonijn.Goap/Interfaces/IAgentEvents.cs#L26) events?

**Comment by Layla-P** [comment]
I think `[IsInRange](https://github.com/crashkonijn/GOAP/blob/master/Package/Runtime/CrashKonijn.Goap/Interfaces/IActionBase.cs#L14)` is okay - but one could update it to be `IsWithinStoppingDistance` if you really wanted to. But `IsInRange` is descriptive enough. 
Similar for the `TargetInRange`.
The `TargetOutOfRange` makes me think that the Target cannot be reached rather than it just hasn't been reached yet. So `TargetNotInRange` may be a better name.

**Comment by crashkonijn** [comment]
Fixed for v3! 🎉
