### ISSUE TITLE
Feature: Add Xml comment's for public methods and properties

### ISSUE THREAD

**Issue by PlatWalker** [crashkonijn/GOAP#169]
Kinda straightforwad. Can you add xml comments to public methods and properties? It's so much easier to just browse code and look up what things doing and not trying to find this one sentence in yours (very nicly done, by the way) documentation? Here is example: 

`public void SetGoal<TGoal>(bool endAction) where TGoal : IGoalBase
{
    this.SetGoal(this.GoapSet.ResolveGoal<TGoal>(), endAction);
}`
What is this bool with endAction? I would need to refer to some place in documentation and it could be just a nice xml 

`/// <summary>
/// Set's goal for agent.
/// </summary>
/// <param name="endAction">does this and this</param>`

so goooooood quality of life update it would be, with a little effort!

**Comment by laurentopia** [comment]
`/// <summary>` & `/// </summary>` are not needed
triple dash is enough to trigger display of comment in IDEs

**Comment by sima995** [comment]
This would indeed be nice. It would mean we don't have to go back and forth looking at the code and trying to find the part in the docs that explains it which is a bit frustrating right now.

**Comment by crashkonijn** [comment]
I just spend some time doing this. I added comments to the following classes:

- AgentBehaviour
- GoapActionProvider
- ActionBase
- SensorsBase classes
- A bunch of XBuilder classes

Are there any other classes you guys regularly use where you'd like to see docs?

**Comment by crashkonijn** [comment]
This has been released by now. If there's more that needs documenting let me know!
