### ISSUE TITLE
If graph viewer is running with previous agent selected then Agent Behaviour is destroyed on play

### ISSUE THREAD

**Issue by Layla-P** [crashkonijn/GOAP#207]
Have the graph viewer open, run game, select agent, stop play.
Press play with the now despawned agent still selected in the graph viewer.

<img width="601" alt="image" src="https://github.com/user-attachments/assets/9cfe90c0-c9b0-4fa8-a4f0-b273fda0d5fe">

**Comment by crashkonijn** [comment]
Hi!

I can't repeat your issue. If this happens again, could you please click on the error and paste the call stack here?

**Comment by crashkonijn** [comment]
Closing this since I have nothing to continue on. If you do get this again, don't hesitate to post again (with the call stack). Thanks!
