### ISSUE TITLE
Goal Reporting as not valid when it should be

### ISSUE THREAD

**Issue by Layla-P** [crashkonijn/GOAP#208]
An action is showing as having conditions met in the Graph view - however the target keeps getting nulled out and the action being marked as invalid.

https://github.com/user-attachments/assets/35c3649e-1c44-4a96-96a9-6ce7c0116948

This Goal/Action was working perfectly prior to the upgrade to V3, I have a similar issue with another Goal/Action which is now not working since the upgrade to V3

**Comment by crashkonijn** [comment]
Hi there!

Can you post your action here?

**Comment by crashkonijn** [comment]
Changes have been released in latest beta!
