### ISSUE TITLE
Bug: Goal Resolution doesn't skip goals that have already been completed

### ISSUE THREAD

**Issue by MrDeflector** [crashkonijn/GOAP#217]
**Describe the bug**
If I have multiple goals and I use the multiple goal configuration the resolve phase appears to keep re-selecting the same goal over and over again. 

**Steps to Reproduce**
1. Create 2 or more goals with the same base cost
2. Ensure both goals have unique conditions
3. Use both goals in a multi goal setup GoapActionProvider.RequestGoal<Goal1, Goal2>()
4. 

**Expected behavior**
When a goal has all its conditions met and the goal has been achieved, it should not be considered as a new goal

**Screenshots**
![image](https://github.com/user-attachments/assets/11ca5b19-e614-4b17-8fad-bdc80d7eedc9)

**Unity Version**
2022.3.20f1.git.6406910

**Unity.Collections Version**
2.4.2

**Package Version**
3.0.4-beta

**Additional context**

**Comment by crashkonijn** [comment]
Changes have been released in latest beta!
