### ISSUE TITLE
Question: disable the cost of distance 

### ISSUE THREAD

**Issue by Smooth-Zhao** [crashkonijn/GOAP#224]
**Expected behavior**
How to disable the effect of distance between actions on cost.

**Package Version**
V2.1.22

**Comment by crashkonijn** [comment]
Hi there!

Thanks for reaching out! There's no way to disable it, but you can set the `DistanceMultiplier` on the `AgentBehaviour` to 0. That should disable the distance cost.

Other than that, it turned out that distance wasn't correctly used in cost, but only for heuristics in v2. This is something that got fixed for the upcoming v3. #170

**Comment by Smooth-Zhao** [comment]
> Hi there!
> 
> Thanks for reaching out! There's no way to disable it, but you can set the `DistanceMultiplier` on the `AgentBehaviour` to 0. That should disable the distance cost.
> 
> Other than that, it turned out that distance wasn't correctly used in cost, but only for heuristics in v2. This is something that got fixed for the upcoming v3. #170

Thanks for your answer!

I have tried to set `DistanceMultiplier` to 0, but nothing happens. 

Do you know why it always executes the left path?

![image](https://github.com/user-attachments/assets/b78e462b-4a6b-4ee0-ad58-fe8c06166126)

**Comment by crashkonijn** [comment]
No, I do not. That does seem weird. I think that it still might have something to do with with distance. I did improve the resolver a lot in v3 though so upgrading might solve your issues.

Btw, may I ask why you've split up and added `MoveTo<x>` actions? What does this solve that doesn't happen when you simply use the targets of the move actions on the executing actions?

**Comment by Smooth-Zhao** [comment]
Actually,it's never used in MoveToAction.I'm going to remove it.

Thanks for your answer! I will try v3 or add more conditions to fix my problem.

**Comment by crashkonijn** [comment]
Hey @Smooth-Zhao,

Did you have more luck with v3?

**Comment by crashkonijn** [comment]
Closing the issue. If you require any further help don't hesitate to open it again or create a new ticket!
