### ISSUE TITLE
Feature: Can you port this to Godot while still using c#?

### ISSUE THREAD

**Issue by gilroff** [crashkonijn/GOAP#229]
I really like the Godot engine and plan to make an NPC world. But the options available now don't seem to be performant or multithreaded.

**Comment by crashkonijn** [comment]
Hi there @gilroff,

Thanks for reaching out!

Unfortunately I have no current plans to port this to Godot. Even though both Godot and Unity can use C#, there's an awful lot of Unity specific code in this repository. It would require separating out and then re-building of all of this, which I simply don't have the time for.

I can't tell what the future holds, but for now I'm closing this ticket as it's not something that I'll do at this time.
