### ISSUE TITLE
Feature: Accessing Components in Sensor

### ISSUE THREAD

**Issue by Unshackled-Games** [crashkonijn/GOAP#231]
I was wondering why there was a difference in the way we access components in Actions and in Senors. Would there be a way to give a class to a sensor with the cached components, like we do in actions? Or is that not possible because of the lifecycle? 

Action: 
![image](https://github.com/user-attachments/assets/7998954d-cf2c-4656-8f35-4480d76b7674)
Sensor:
![image](https://github.com/user-attachments/assets/309b3d18-44cb-4da6-832b-4ddf643416c8)

**Comment by crashkonijn** [comment]
Hi!

Implementing this would make it quite a bit more complex for me to manage the sensors. The cached references is supposed to solve this problem for you.

If you do want some extra data you could probably implement your own MonoBehaviour, add that to each agent and then get the reference to that.
