### ISSUE TITLE
Abstract base classes added to agentTypeConfigFactories in GoapBehaviour

### ISSUE THREAD

**Issue by Layla-P** [crashkonijn/GOAP#271]
Version 3.0.12-Beta

As mentioned on discord the `agentTypeConfigFactories` in the `GoapBehaviour` is adding two instances of the abstract base class.
This causes exceptions.

![image](https://github.com/user-attachments/assets/d5c895f4-0150-4ace-98a0-7e8ccf47551c)

![image](https://github.com/user-attachments/assets/f967ca7a-ecad-4475-8853-90d04174729e)

Suggested update for quick fix - or find why the base classes are being picked up.

```csharp
        private void CreateAgentTypes()
        {
            var agentTypeFactory = new AgentTypeFactory(this.Config);

            this.agentTypeConfigFactories.ForEach(factory =>
            {
                if (factory != null)
                    this.Register(agentTypeFactory.Create(factory.Create()));
            });
        }
```

**Comment by crashkonijn** [comment]
Fixed in 3.0.19-beta
