### ISSUE TITLE
Bug: Problems with Async event behavior

### ISSUE THREAD

**Issue by Unshackled-Games** [crashkonijn/GOAP#279]
Okay now I am certain that I found a problem that is not from me (I believe) :D

![Screenshot 2024-10-11 120128](https://github.com/user-attachments/assets/c75250e9-a453-4fa4-a3bf-2a879488e26a)

When I pause and then start playmode one of the 4 characters I use already gets event requests from the AgentBehaviour. 

Because 3 of the 4 dont get event callbacks I think this behaviour is uninteded.

**Comment by Unshackled-Games** [comment]
It was my mistake...

**Comment by crashkonijn** [comment]
Glad you found the problem!

For next time; please be a bit more descriptive on the steps to trigger this, what you expect and what is actually happening. Without further context it would've been hard for me to duplicate the issue and fix it. I was just about to ask for more info.

Anyway, glad I could be your rubber duck today!

![image](https://github.com/user-attachments/assets/f63099da-973e-4dd4-acd9-9619c64f32ef)
