### ISSUE TITLE
V3 Bug: AgentBehaviour Events.OnTargetChanged not work when use ProactiveController

### ISSUE THREAD

**Issue by Capytara** [crashkonijn/GOAP#280]
When use `ProactiveController` , I continuously change the value of `TargetKey` through `TargetSensor`, but `AgentBehaviour Events.OnTargetChanged` will only be called once after the current Action is finished, not at the same frequency as `TargetSensor`.

TargetSensor:
```C#
public class ClosestAttackableTargetSensor : LocalTargetSensorBase
{
    public override void Created() { }
    public override void Update() { }

    public override ITarget Sense(IActionReceiver agent, IComponentReference references, ITarget existingTarget)
    {
        var closetPosition = references.GetCachedComponent<Enemy>().ClosestAttackablePosition();
        return closetPosition.HasValue ? new PositionTarget(closetPosition.Value) : null;
    }
}
```

I read source code and change TargetSensor to this, `AgentBehaviour.Events.OnTargetChanged` can work：
```c#
public class ClosestAttackableTargetSensor : LocalTargetSensorBase
{
    public override void Created() { }
    public override void Update() { }

    public override ITarget Sense(IActionReceiver agent, IComponentReference references, ITarget existingTarget)
    {
        var closetPosition = references.GetCachedComponent<Enemy>().ClosestAttackablePosition();
        if (agent.ActionState.Data != null)
            agent.ActionState.Data.Target = closetPosition.HasValue ? new PositionTarget(closetPosition.Value) : existingTarget;
        return closetPosition.HasValue ? new PositionTarget(closetPosition.Value) : null;
    }
}
```
But it looks a little strange.

**Comment by crashkonijn** [comment]
In case anyone else finds this, we discussed this on Discord. When te sensors are re-run, the value on an action doesn't update as this would break the data flow of actions.

This was the answer I gave on Discord, that solved his issues:

> 
> The existingTarget is the ITarget instance/value that's currently in the WorldData for the same key the sensor provides a value for. (AKA the previously returned instance).
> 
> The system itself doesn't provide this value, so the first time it's run you have to provide it yourself:
> 
> ```csharp
> public override ITarget Sense(IActionReceiver agent, IComponentReference references, ITarget existingTarget)
> {
>     var random = this.GetRandomPosition(agent);
>     
>     // If the existing target is a `PositionTarget`, we can reuse it and just update the position.
>     if (existingTarget is PositionTarget positionTarget)
>     {
>         return positionTarget.SetPosition(random);
>     }
>     
>     return new PositionTarget(random);
> }
> ```
> When an action starts, a new instance of the corresponding IActionData is created, and the ITarget value on there is set from the WorldData. The OnTargetChanged event is based on the value that's on the action data.

> So lets say we start running the game, the order of things might look like this:
> 
> Resolver is run:
> - Sensors are updated (FollowPlayerActionTarget is provided)
> - FollowPlayerAction is picked
> - ActionData.Target is set to FollowPlayerActionTarget
> - System detects a new instance of ITarget is being used, sends out the OnTargetChangedEvent
> - MoveBehaviour stores the ITarget value, reads the target.Position value.
> 
> X amount of frames:
> - MoveBehaviour reads the target.Position value and inputs that into the move/pathfinding
> 
> Resolver is run again:
> - Sensors are update (You re-use the existing  FollowPlayerActionTarget, updating it's position)
> - Action is the same, doesn't update the action (or target) and updates no event
> 
> X amount of frames:
> MoveBehaviour reads the target.Position value and inputs that into the move/pathfinding (This is now the updated position from the last time the sensor was run)
> 
> If I have to guess I would say that you're not storing the ITarget instance in your move behaviour, but are storing/using the target.Position value instead?
> 
> The system doesn't throw an event when the position updates, it throws and event when the instance of ITarget being used changes.
> 
> You have to keep reading the target.Position in the Update method of your MoveBehaviour
> For example:
> 
> ```csharp
> public class AgentMoveBehaviour : MonoBehaviour
> {
>     private AgentBehaviour agent;
>     private ITarget currentTarget;
>     private bool shouldMove;
> 
>     private void Awake()
>     {
>         this.agent = this.GetComponent<AgentBehaviour>();
>     }
> 
>     private void OnEnable()
>     {
>         this.agent.Events.OnTargetInRange += this.OnTargetInRange;
>         this.agent.Events.OnTargetChanged += this.OnTargetChanged;
>         this.agent.Events.OnTargetNotInRange += this.TargetNotInRange;
>         this.agent.Events.OnTargetLost += this.TargetLost;
>     }
> 
>     private void OnDisable()
>     {
>         this.agent.Events.OnTargetInRange -= this.OnTargetInRange;
>         this.agent.Events.OnTargetChanged -= this.OnTargetChanged;
>         this.agent.Events.OnTargetNotInRange -= this.TargetNotInRange;
>         this.agent.Events.OnTargetLost -= this.TargetLost;
>     }
>     
>     private void TargetLost()
>     {
>         this.currentTarget = null;
>         this.shouldMove = false;
>     }
> 
>     private void OnTargetInRange(ITarget target)
>     {
>         this.shouldMove = false;
>     }
> 
>     private void OnTargetChanged(ITarget target, bool inRange)
>     {
>         this.currentTarget = target;
>         this.shouldMove = !inRange;
>     }
> 
>     private void TargetNotInRange(ITarget target)
>     {
>         this.shouldMove = true;
>     }
> 
>     public void Update()
>     {
>         if (!this.shouldMove)
>             return;
>         
>         if (this.currentTarget == null)
>             return;
>         
>         this.transform.position = Vector3.MoveTowards(this.transform.position, new Vector3(this.currentTarget.Position.x, this.transform.position.y, this.currentTarget.Position.z), Time.deltaTime);
>     }
> }
> ```
