### ISSUE TITLE
Question: Issue initializing GoapSet

### ISSUE THREAD

**Issue by mattemoore** [crashkonijn/GOAP#281]
**Expected behavior**
I think I followed the simple example using ScriptableObjects correctly but have an issue with initializing GoapSet.

- Goap GameObject created w/ Goap Runner Behaviour component, w/ no config initializer and no config factories
- GoapSet GameObject created w/ Goap Set Behaviour component, config points to PlayerSet and runner is Goap GameObject
- Enemy GameObject created, this is a prefab with some overrides, added Agent Behaviour and AI Player Brain Script.
- `AIPlayerBrain.cs`

```c#
using Assets.Scripts;
using CrashKonijn.Goap.Behaviours;
using Demos.Shared.Behaviours;
using Demos.Shared.Goals;
using UnityEngine;

namespace Assets.Scripts.GOAP
{
    public class AIPlayerBrain : MonoBehaviour
    {
        private AgentBehaviour _agent;
        private PlayerController _playerController;

        private void Awake()
        {
            _agent = this.GetComponent<AgentBehaviour>();
            _playerController = this.GetComponent<PlayerController>();
        }

        private void Start()
        {
            _agent.SetGoal<GetLoosePuckGoal>(false);
        }

        private void Update()
        {
            //if (this.hunger.hunger > 80)
            //{
            //    this._agent.SetGoal<FixHungerGoal>(false);
            //    return;
            //}

            //if (this.hunger.hunger < 20)
            //    this._agent.SetGoal<WanderGoal>(true);
        }
    }
}
```

- `PlayerSet` is a `Goap Set Config`, with `GetLoosePuckAction`, `GetLoosePuckGoal`, `IsPuckLooseWorldSensor`, `IsPuckLooseWorldKey`, `LoosePuckTargetSensor`, and `LoosePuckTargetKey`
- `PlayerSet` validates without any errors
-  ![image](https://github.com/user-attachments/assets/05b4856f-e83a-40f0-9f35-e9d399fbf401)
- ![image](https://github.com/user-attachments/assets/975b8d7d-55bf-46e1-935f-f7f54bb83088)
- `GetLoosePuckGoal.cs`
```C#
using CrashKonijn.Goap.Behaviours;

namespace Assets.Scripts.GOAP
{
    public class GetLoosePuckGoal : GoalBase
    {
    }
}
```
- `GetLoosePuckAction.cs`
```C#
using CrashKonijn.Goap.Behaviours;
using CrashKonijn.Goap.Classes;
using CrashKonijn.Goap.Enums;
using CrashKonijn.Goap.Interfaces;
using UnityEngine;

namespace Assets.Scripts.GOAP
{
    public class GetLoosePuckAction : ActionBase<GetLoosePuckAction.Data>
    {
        // You can implement a custom cost function. This is useful if you want to add dynamic costs to the action.
        public override float GetCost(IMonoAgent agent, IComponentReference references)
        {
            return Vector3.Distance(agent.transform.position, references.GetCachedComponent<PlayerController>().Puck.transform.position);
        }

        // This method is called to determine if the _agent is in range for the action. It is called every frame while the action is running.
        // This could be used to perform a physics check to actually guarantee line of sight for example.
        public override bool IsInRange(IMonoAgent agent, float distance, IActionData data, IComponentReference references)
        {
            return distance <= this.Config.InRange;
        }

        // This methods is called when the action is created. It is used to initialize the action.
        public override void Created()
        {
        }

        // This method is called when the action is started. It is used to initialize the action.
        public override void Start(IMonoAgent agent, Data data)
        {
            data.PlayerController = agent.GetComponent<PlayerController>();
        }

        public override ActionRunState Perform(IMonoAgent agent, Data data, ActionContext context)
        {
            if (data.PlayerController.HasPuck)
            {
                return ActionRunState.Stop;
            }
            else
            {
                Vector3 directionToPuck = data.PlayerController.Puck.transform.position - agent.transform.position;
                data.PlayerController.Skate(directionToPuck);
                return ActionRunState.Continue;
            }
        }

        // This method is called when the action is stopped. It is used to clean up the action.
        public override void End(IMonoAgent agent, Data data)
        {
        }

        // Action data class. It stores the state of the action for a single _agent. This data is not persistent between agents or between multiple runs of the same action.
        public class Data : IActionData
        {
            // The target position of the action. This is set by the planner.
            public ITarget Target { get; set; }
            public PlayerController PlayerController { get; set; }
        }
    }
}
```
-`IsPuckLooseWorldSensor.cs`
```C#
using CrashKonijn.Goap.Interfaces;
using CrashKonijn.Goap.Sensors;
using Demos.Shared.Behaviours;
using UnityEngine;

namespace Assets.Scripts.GOAP
{
    public class IsPuckLooseSensor : GlobalWorldSensorBase
    {
        PlayerController _playerController;

        public override void Created()
        {
            _playerController = GameObject.Find("Player").GetComponent<PlayerController>();
        }

        public override SenseValue Sense()
        {
            return _playerController.HasPuck;
        }
    }
}
```
-`LoosePuckTargetSensor.cs`
```c#
using CrashKonijn.Goap.Behaviours;
using CrashKonijn.Goap.Classes;
using CrashKonijn.Goap.Classes.References;
using CrashKonijn.Goap.Interfaces;
using CrashKonijn.Goap.Sensors;
using Demos.Simple.Behaviours;
using UnityEngine;

namespace Assets.Scripts.GOAP
{
    public class LoosePuckTargetSensor : LocalTargetSensorBase
    {
        private GameObject _puck;

        public override void Created()
        {
            _puck = GameObject.Find("Puck");
        }

        public override void Update()
        {
        }

        public override ITarget Sense(IMonoAgent agent, IComponentReference references)
        {
            if (_puck is null)
                return null;

            return new TransformTarget(_puck.transform);
        }
    }
}
```
- I have not implemented a move behaviour yet like in the sample but I figure that the initialization errors in the screenshots before are related to things upstream from a move behaviour.
- After the errors are displayed below I can see that the Agent Behaviour attached to my Enemy gameobject is disabled in the Editor
- If I enable it i get the following error which indicates that no GoapSet is assigned but there is one assigned as per the screenshot:
![image](https://github.com/user-attachments/assets/b86cd208-19fb-4a18-8722-a3bee39112bd)

**Screenshots**
![image](https://github.com/user-attachments/assets/520e437c-d5f2-4214-a4da-e1e44c1de373)
![image](https://github.com/user-attachments/assets/fbe0a571-5f6a-4fc0-9484-6bace750828b)
![image](https://github.com/user-attachments/assets/b4ba919c-6fe5-4ef2-b906-c179b7ce198e)

**Unity Version**
2022.3.37f1

**Unity.Collections Version**
Not sure how to do this.

**Package Version**
2.1.19
![image](https://github.com/user-attachments/assets/82b7b6d8-96ec-4ac9-b03c-63b122e4e345)

**Additional context**

**Comment by mattemoore** [comment]
Bit more information:

- ClassResolver works for `IsPuckLooseWorldSensor` 
- ClassResolver fails for `LoosePuckTargetSensor` as `Type.GetType(x.ClassType)` returns null which can't be passed to `Activator.CreateInstance()`.  Note that `x.ClassType` is set to "LoosePuckTargetSensor, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null".

**Comment by mattemoore** [comment]
And LoosePuckTargetSensor ScriptableObject has empty value for Class. 
Thanks for the opportunity for rubber ducking.

Perhaps some type of validation around there would help others in future?  It is a bit odd to see GoapSet errors in log when issue was incomplete config of ScriptableObject.

**Comment by crashkonijn** [comment]
Hey!

I'm on vacation at the moment, so I can't really go in depth and look at your question properly.

From your last comment, can I presume the missing class was the issue?

With regards of better validation, that's already been done for v3. Setup should be a lot easier as well.

V3 is almost out of beta, if you're just starting out you might want to upgrade already 😁

**Comment by mattemoore** [comment]
Yes the missing class was the fix.  I've re-started with v3.  Will submit some issues/questions in another thread.
