### ISSUE TITLE
Bug: System.IndexOutOfRangeExecption

### ISSUE THREAD

**Issue by mattemoore** [crashkonijn/GOAP#282]
**Describe the bug**
Followed the code version of getting started for v3, modifying for my needs as I went.  When I start the scene i get a System.IndexOutOfRangeException().
![image](https://github.com/user-attachments/assets/bdc97904-4801-4df6-8e26-602e7cb925a4)

```
System.IndexOutOfRangeException: Index 1881650848 is out of range of '-1' Length.
This Exception was thrown from a job compiled with Burst, which has limited exception support.
0x00007ffa9b4265fe (d2fa8945f4a76ef3707e84c2fa9da33) burst_Abort_Trampoline
0x00007ffa9b424939 (d2fa8945f4a76ef3707e84c2fa9da33) Unity.Collections.NativeArray`1<bool>.FailOutOfRangeError (at C:/Code/hockey3d/Hockey3D/Library/PackageCache/com.unity.burst@1.8.16/.Runtime/unknown/unknown:0)
0x00007ffa9b421a27 (d2fa8945f4a76ef3707e84c2fa9da33) Unity.Jobs.IJobExtensions.JobStruct`1<CrashKonijn.Goap.Resolver.GraphResolverJob>.Execute(ref CrashKonijn.Goap.Resolver.GraphResolverJob data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, ref Unity.Jobs.LowLevel.Unsafe.JobRanges ranges, int jobIndex) -> void_0d64390541958b43604801c180219108 from UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (at C:/Code/hockey3d/Hockey3D/Library/PackageCache/com.unity.burst@1.8.16/.Runtime/unknown/unknown:0)
0x00007ffa9b42109d (d2fa8945f4a76ef3707e84c2fa9da33) 11ea8603ecd1fe278548ab043a783cf2
0x00007ff709994a32 (Unity) ExecuteJob
0x00007ff709995e1f (Unity) ForwardJobToManaged
0x00007ff709991c2a (Unity) ujob_execute_job
0x00007ff70999105d (Unity) lane_guts
0x00007ff709993cb4 (Unity) worker_thread_routine
0x00007ff709bbf61b (Unity) Thread::RunThreadWrapper
0x00007ffae232257d (KERNEL32) BaseThreadInitThunk
0x00007ffae31aaf08 (ntdll) RtlUserThreadStart
```

**Expected behavior**
No Index out of range exception.

**Screenshots**
![image](https://github.com/user-attachments/assets/f01e8684-36a5-4f50-8e23-4fd4dfd9fbcf)

**Unity Version**
2022.3.37f1

**Unity.Collections Version**
Not sure how to get this version number.

**Package Version**
![image](https://github.com/user-attachments/assets/f3b11a22-f076-46c1-9c0b-e3900b7c03f8)

**Additional context**
Additional context available upon request.

**Comment by crashkonijn** [comment]
Hey @mattemoore!

Thanks for reaching out!

I'm currently on vacation for another week, so I can't have a proper look at this right now.

Crashing the resolver is really hard to do, so I'm really interested to see how you did it. (This should also be the reason you don't get any events thrown).

Something very specific is causing this and based on the information provided I won't be able to figure out what it is exactly.

Can you provide me with a small unity project that breaks like this, so I can fix this when I get back?

Thanks in advance!

**Comment by mattemoore** [comment]
Enjoy your vacation.  I've added you as contributor to my private git repo that has just the beginnings of the game I'm working on.

**Comment by mattemoore** [comment]
This error goes away after restarting Unity.  It's possible there is an issue if you upgrade from v2 to v3 and not restart Unity.  I still have the event not firing issue though.  Will add some more info over there.  Enjoy vacation.
