### ISSUE TITLE
Bug: AgentMoveBehaviour Events not firing

### ISSUE THREAD

**Issue by mattemoore** [crashkonijn/GOAP#283]
**Describe the bug**
The various target related events in my agent move behaviour script are not firing.  Awake and OnEnable events fire.  None of the target events fire thus `shouldMove` is always false.

**Steps to Reproduce**
Followed tutorial.  Modified to my needs as needed.

**Expected behavior**
Target events fire which trigger agent movement.

**Screenshots**
![image](https://github.com/user-attachments/assets/7101fbee-aa82-433a-a382-79c0ecb08432)
![image](https://github.com/user-attachments/assets/cdd55bc2-60fa-4be5-8174-b52519087e75)
![image](https://github.com/user-attachments/assets/17975b09-571f-419c-afb7-5104c9b00650)

```C#
using Assets.Scripts;
using CrashKonijn.Agent.Core;
using CrashKonijn.Agent.Runtime;
using UnityEngine;

namespace Assets.Scripts.GOAP
{
    public class AgentMoveBehaviour : MonoBehaviour
    {
        PlayerController _playerController;
        private AgentBehaviour agent;
        private ITarget currentTarget;
        private bool shouldMove;

        private void Awake()
        {
            Debug.Log($"Awake");
            _playerController = GetComponent<PlayerController>();
            this.agent = this.GetComponent<AgentBehaviour>();
        }

        private void OnEnable()
        {
            Debug.Log($"OnEnable");
            this.agent.Events.OnTargetInRange += this.OnTargetInRange;
            this.agent.Events.OnTargetChanged += this.OnTargetChanged;
            this.agent.Events.OnTargetNotInRange += this.TargetNotInRange;
            this.agent.Events.OnTargetLost += this.TargetLost;
        }

        private void OnDisable()
        {
            Debug.Log($"OnDisable");
            this.agent.Events.OnTargetInRange -= this.OnTargetInRange;
            this.agent.Events.OnTargetChanged -= this.OnTargetChanged;
            this.agent.Events.OnTargetNotInRange -= this.TargetNotInRange;
            this.agent.Events.OnTargetLost -= this.TargetLost;
        }

        private void TargetLost()
        {
            Debug.Log($"TargetLost");
            this.currentTarget = null;
            this.shouldMove = false;
        }

        private void OnTargetInRange(ITarget target)
        {
            Debug.Log($"OnTargetInRange");
            this.shouldMove = false;
        }

        private void OnTargetChanged(ITarget target, bool inRange)
        {
            Debug.Log($"OnTargetChanged");
            this.currentTarget = target;
            this.shouldMove = !inRange;
        }

        private void TargetNotInRange(ITarget target)
        {
            Debug.Log($"TargetNotInRange");
            this.shouldMove = true;
        }

        public void Update()
        {

            if (!this.shouldMove)
            {
                
                return;
            }

            if (this.currentTarget == null)
            {
                
                return;
            }
            
            Vector3 directionToTarget = _playerController.Puck.transform.position - this.transform.position;
            _playerController.Skate(directionToTarget);
        }

        private void OnDrawGizmos()
        {
            if (this.currentTarget == null)
                return;

            Gizmos.DrawLine(this.transform.position, this.currentTarget.Position);
        }
    }
}
```

**Unity Version**
2022.3.35f1

**Unity.Collections Version**
Not sure how to retrieve this.

**Package Version**
In screenshots section.

**Additional context**
Additional context available upon request.

**Comment by mattemoore** [comment]
Added in screenshots from inspector.

![image](https://github.com/user-attachments/assets/63f7a087-f88a-4dde-bdf2-6c9465c7c4cb)
![image](https://github.com/user-attachments/assets/a300a71c-9818-43f3-b846-2fe4aa98068f)
![image](https://github.com/user-attachments/assets/41a2b230-1ccc-4ff8-82cc-50c2da0d5302)

**Comment by mattemoore** [comment]
Tried the scriptables approach and same issue:
![image](https://github.com/user-attachments/assets/8731edaa-5ddb-476b-b472-8d8c18352365)
![image](https://github.com/user-attachments/assets/a3bf9ce6-1e37-4cd0-a717-335487a7e055)
![image](https://github.com/user-attachments/assets/5ca79675-65e9-427c-be13-6486a5c37ed9)
![image](https://github.com/user-attachments/assets/b9d87b95-3d49-49bc-9e90-99fd688efbbd)
![image](https://github.com/user-attachments/assets/42e34e02-4056-4bd5-a82a-cee45435e23e)

**Comment by crashkonijn** [comment]
Hey!

The logs on the GoapActionProvider show that it was unable to find a valid action to perform.

Your goal already has its conditions met and is already completed and as such won't search for anything to do.

Since it doesn't find a valid action, you're not getting any move events 😁

**Comment by mattemoore** [comment]
Fascinating.  I was looking at the goal condition in the opposite way.  I was looking at the goal condition as when the goal would be active not completed and thus not "enabled".

**Comment by crashkonijn** [comment]
Glad we figured it out!

I should probably spend some more time explaining this in the docs.
