### ISSUE TITLE
Feature: Allow to keep an action performing even if the target became invalid at some point

### ISSUE THREAD

**Issue by Racines** [crashkonijn/GOAP#285]
**Is your feature request related to a problem? Please describe.**
My use case is to collect an item, but the item is destroyed during the collect animation, but I don't want to exit the current action until the whole animation is done. (I am using proactive controller by the way)

**Describe the solution you'd like**
in GoapActionBase be able to disable internal checking

**Describe alternatives you've considered**
using the ITarget.IsValid(), adding ForceValidation boolean that is set to true when BeforePerform() and set to false at End() 
but sensor have resend existing target while it's valid and force invalidation at end of the action.

**Additional context**
Discussion on discord: (https://discord.com/channels/1093598557480685578/1093599290829590679/1299297138307633245)

**Comment by crashkonijn** [comment]
Has been released in 3.0.21-beta!
