### ISSUE TITLE
Question: V3 stability

### ISSUE THREAD

**Issue by sima995** [crashkonijn/GOAP#303]
Hi @crashkonijn!

First of all thanks for this great asset!

We're about to transition from a behaviour-tree approach to your GOAP system in our upcoming game. I was wondering how stable the current v3 release is. The new features look very promising, but I'd prefer stability over the new features.

Is there an ETA on an officially stable release?

Thank you very much and keep up the good work!

Marcell

**Comment by crashkonijn** [comment]
Hey!

Thanks for reaching out and considering this package!

V3 is feature complete, I was waiting for the unity asset store to accept the v3 package.

I am planning to release next week 😁

**Comment by sima995** [comment]
Excellent news! Thanks for getting back to me, and congratulations on the upcoming release!
