### ISSUE TITLE
Problems when importing from git

### ISSUE THREAD

**Issue by Francosinus** [crashkonijn/GOAP#37]
I wanted to add the package via "Add package from git URL" in the package manager, but all the README.md files don't have a meta file which throws several errors and the asset will be ignored. Would be nice if you could add them. 

Example output:
_Asset Packages/com.crashkonijn.goap/Documentation/Classes/README.md has no meta file, but it's in an immutable folder. The asset will be ignored._

Also this warning appears:
_Packages/com.crashkonijn.goap/Editor/CrashKonijn.Goap.Editor/Styles/NodeViewer.uss (line 36): warning: Unknown property 'weight' (did you mean 'height'?)
    weight: 100_

**Comment by crashkonijn** [comment]
Hey @Francosinus, thanks for reporting this!

Which version of Unity are you using? Thanks!

**Comment by Francosinus** [comment]
I'm using 2022.2.2, your demo projects work fine with that. It's not working with older versions right? I have a project with version 2021.3.14 as well and wanted to use it for this, but changing to a newer version should be no problem I guess

**Comment by crashkonijn** [comment]
Thanks for the update. Since v2.1 unity 2021.3 should also work, although I do believe there's currently an issue with how the node viewer is rendered there.

**Comment by crashkonijn** [comment]
@Francosinus I believe the warnings should be gone now!

**Comment by Francosinus** [comment]
Thanks, all warnings are gone :) I really appreciate your work
