### ISSUE TITLE
On Perform end event

### ISSUE THREAD

**Issue by slavaobninsk** [crashkonijn/GOAP#4]
Hello, thanks for implementation GOAP, how i can get Perform "start" and "end" event from GOAP action?

I want Play animation on Perform start and disable this on Perform end.

**Comment by slavaobninsk** [comment]
Or can you added example with animation component

**Comment by crashkonijn** [comment]
Hello @slavaobninsk, thanks for checking out this project!

Each action has a [OnStart](https://github.com/crashkonijn/GOAP/blob/66152e40d7c10d9d4ef31bb1a4f287fc74ef430f/GOAP/Core/GoapAction.cs#L443) and [OnEnd](https://github.com/crashkonijn/GOAP/blob/66152e40d7c10d9d4ef31bb1a4f287fc74ef430f/GOAP/Core/GoapAction.cs#L452) function that you extend to use as your callback.

Is that what you need? :)
