### ISSUE TITLE
Issue: Node Viewer Breaks Second Time You Play

### ISSUE THREAD

**Issue by simeonradivoev** [crashkonijn/GOAP#43]
When I play the editor (2022.2.8f1) for the first time the Node Viewer show the agent fine and when I click on it the tree works as intended.
The issue is when I start the game again, the agent is listed, but when I click on it the action tree doesn't show up.
![image](https://github.com/crashkonijn/GOAP/assets/9950198/5e22ce8b-af31-4823-869e-584f3213181e)

**Comment by crashkonijn** [comment]
Thanks for reporting the issue @simeonradivoev!

Could you confirm that this branch fixes the issue?

`https://github.com/crashkonijn/GOAP.git?path=/Package#fix/node-viewer-breaking`

**Comment by simeonradivoev** [comment]
It does, yes.
