### ISSUE TITLE
Feature: Custom Distance Check

### ISSUE THREAD

**Issue by simeonradivoev** [crashkonijn/GOAP#44]
Would be nice if there was a way to adjust how the distance to a target is calculated. For example, when you use `NavMeshAgent` you want to  use its `remainingDistance`.

Would also be neat if you can prematurely tell if a target is reached, say from the action itself. Example: Maybe you want the agent to stop when they see the target, instead of always stopping at a given distance. 
Well, you can probably just return infinity as the stopping distance and that would basically act the same🤔

**Comment by crashkonijn** [comment]
It's impossible to connect something other than `Vector3.Distance` (or similar) as a weight in the planner, but on the agent it should indeed be possible.

The `GetDistance()` and `IsInRange()` methods on an agent could be moved to an interface implementation. I think something like this would be sufficient?

```csharp
public interface IAgentDistance {
    public float GetDistance(IMonoAgent agent, IComponentReferences references, ITarget target);
    public bool IsInRange(IMonoAgent agent, IComponentReferences references, ITarget target);
}
```

**Comment by simeonradivoev** [comment]
yea that would be great

**Comment by crashkonijn** [comment]
I think we could do an `GetComponent<IAgentDistance>` and either use that or use the default implementation? That way you'd just implement this on a MonoBehaviour and add it to your agent.

**Comment by crashkonijn** [comment]
Hi there!

Could you check if this PR lets you do the things you requested? Docs are in the PR as well!

`https://github.com/crashkonijn/GOAP.git?path=/Package#feature/custom-distance-and-range-check`

**Comment by simeonradivoev** [comment]
Looks pretty good. Good work!
