### ISSUE TITLE
HAS_OBJECT Not updating

### ISSUE THREAD

**Issue by mlarney** [crashkonijn/GOAP#5]
As i was running the example and trying to edit it a little bit, i found that even though the AI are moving to the 'throwable' and preforming the action of 'GrabItem', HAS_OBJECT doesn't ever get set to true. I was hoping you could point me in the right direction as to how or where this is supposed to update the variable from the "Effects" so that it becomes true.

Thank you!

**Comment by jrmacgill** [comment]
I've been playing too.... the 'perform' code is missing so the state is never updated.

I played with adding code to ThrowAtPlayerAction
```
public override void Perform()
        {
            agent.dataSet.SetData(GoapAction.Effects.HAS_OBJECT, false);
            agent.dataSet.SetData(Effects.KNOCKED_OUT_PLAYER + targetPlayerId, true);
        }
```
Which does update the state for that agent... allowing it to try killing the player.  But dataSet is not shared between agents so state in all data sets would have to be updated instead...

**Comment by crashkonijn** [comment]
Closing this issue, I just released a completely rebuild of this project!

There are multiple, more complete examples now (as well as extensive docs!)
