### ISSUE TITLE
Bug: Local Sensor Not Called

### ISSUE THREAD

**Issue by simeonradivoev** [crashkonijn/GOAP#51]
**Describe the bug**
Local World Sensor is not updated, and the main action stalls. The sensor is never called. In the Screenshot below the action is `ShootAction` and the key is `InCooldown`. The `InCooldown` is updated per update, but for some reason even the sensor's `Sense` method is not called.

**Steps to Reproduce**
1.  Change the local sensor value from the outsdie.
2. Action has an old sensor value and it stalls.

**Expected behavior**
The local world sensor should update even even if there are no current actions. 

**Screenshots**
![image](https://github.com/crashkonijn/GOAP/assets/9950198/663e970b-8e66-4d58-a7d0-17ed4f650c45)

**Unity Version**
2022.2.8f

**Package Version**
2.1.5

**Additional context**

**Comment by crashkonijn** [comment]
Thanks for the report.

I'l have a look at it tomorrow!

**Comment by simeonradivoev** [comment]
🤔 if the agent finds no actions, should it continue to try and complete said goal or just stop doing anything?
I can get around this by hooking up to the `OnNoActionFound` and calling `EndAction` on the agent. That enqueues them right back to try and find new actions.

**Comment by crashkonijn** [comment]
The agent only enqueues for the resolver after an action is completed. If it finds no action and you don't call endaction it shouldn't requeue.

Best practice is to choose another goal when the OnNoAction event is thrown

**Comment by simeonradivoev** [comment]
ok so it's expected, will close it.

**Comment by simeonradivoev** [comment]
btw is the condition on the goal increased by the action that has the effect for that key?

**Comment by crashkonijn** [comment]
No the action doesn't know how much something changed. For planning it only know whether the effect is positive or negative.

The sensor is re-run for the next resolve.

**Comment by simeonradivoev** [comment]
well for the goal condition you don't need to define a sensor

**Comment by crashkonijn** [comment]
You don't have to, but you can if you want the goal to complete and the OnGoalComple event to be thrown

**Comment by simeonradivoev** [comment]
another related question, how do you get an `IWorldKey` from an action to set its state? This seems like a very common use case scenario, an action has an effect, and you need to actually do the effect in the action. Do we always have to use an external component to store the values so we can edit them from actions?

**Comment by crashkonijn** [comment]
Yes, I do not recommend using the GOAP state as the source of your actual game state. It should just be a compiled version which is only updated when the resolver is run.
