### ISSUE TITLE
Bug: Editor Console states memory leak at start (rare) or after exiting play mode (often)

### ISSUE THREAD

**Issue by yyy1963** [crashkonijn/GOAP#60]
System is Windows 11,  i7-6700, GTX9800ti with 16GBytes of RAM
Unity version is 2022.3.0f1
Using URP
No other asset except GOAP (store version 2.1.5) is imported to project
Unity.Collections Version 1.2.4

Not always reproducible, but more likely to happen when CPU is stressed.

Attempting to test performance with more agents, the following is added to Start() of AgentSpawnBehaviour.cs for the Complex Demo scene:

for (int i = 0; i < 200; i++) {
  this.SpawnAgent(SetIds.Cleaner, ComplexAgentBrain.AgentType.Cleaner, this.cleanerColor);
}

The following error is only observed once at start:

Leak Detected : TempJob allocates 4 individual allocations. To find out more please enable 'Jobs/LeakDetection/Full StackTraces' and reproduce the leak again.

After in play mode for one or 2 minutes, exit the play mode.
The following happens often  after exiting play mode:

ObjectDisposedException: The Unity.Collections.NativeList`1[CrashKonijn.Goap.Resolver.NodeData] has been deallocated, it is not allowed to access it
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckGetSecondaryDataPointerAndThrow (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) (at <6c9b376c3fca40b787e8c1a2133bf243>:0)
Unity.Collections.NativeList`1[T].AsArray () (at ./Library/PackageCache/com.unity.collections@1.2.4/Unity.Collections/NativeList.cs:607)
Unity.Collections.NativeList`1[T].GetEnumerator () (at ./Library/PackageCache/com.unity.collections@1.2.4/Unity.Collections/NativeList.cs:743)
CrashKonijn.Goap.Resolver.ResolveHandle.Complete () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap.Resolver/ResolveHandle.cs:51)
CrashKonijn.Goap.Classes.Runners.GoapSetJobRunner.Dispose () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs:146)
CrashKonijn.Goap.Classes.Runners.GoapRunner.Dispose () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs:53)
CrashKonijn.Goap.Behaviours.GoapRunnerBehaviour.OnDestroy () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs:56)

The above error is followed by the error below multiple times:

A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details. Leak tracking may be enabled via `Unity.Collections.NativeLeakDetection.Mode` or from the editor preferences menu Edit > Preferences > Jobs > Leak Detection Level.

The following are probably due to lack of null check, so may not be related to the issue stated above, but happens within same tests:

NullReferenceException: Object reference not set to an instance of an object
Demos.Complex.Actions.HaulItemAction.Start (CrashKonijn.Goap.Interfaces.IMonoAgent agent, Demos.Complex.Actions.HaulItemAction+Data data) (at Assets/CrashKonijn/GOAP/Demos/Complex/Actions/HaulItemAction.cs:32)
CrashKonijn.Goap.Behaviours.ActionBase`1[TActionData].Start (CrashKonijn.Goap.Interfaces.IMonoAgent agent, CrashKonijn.Goap.Interfaces.IActionData data) (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/ActionBase.cs:25)
CrashKonijn.Goap.Behaviours.AgentBehaviour.SetAction (CrashKonijn.Goap.Interfaces.IActionBase action, System.Collections.Generic.List`1[T] path, CrashKonijn.Goap.Interfaces.ITarget target) (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs:212)
CrashKonijn.Goap.Classes.Runners.GoapSetJobRunner.Complete () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Classes/Runners/GoapSetJobRunner.cs:138)
CrashKonijn.Goap.Classes.Runners.GoapRunner.Complete () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs:43)
CrashKonijn.Goap.Behaviours.GoapRunnerBehaviour.LateUpdate () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs:51)

NullReferenceException: Object reference not set to an instance of an object
Demos.Complex.Actions.HaulItemAction.MoveToItem (CrashKonijn.Goap.Interfaces.IMonoAgent agent, Demos.Complex.Actions.HaulItemAction+Data data) (at Assets/CrashKonijn/GOAP/Demos/Complex/Actions/HaulItemAction.cs:58)
Demos.Complex.Actions.HaulItemAction.Perform (CrashKonijn.Goap.Interfaces.IMonoAgent agent, Demos.Complex.Actions.HaulItemAction+Data data, CrashKonijn.Goap.Classes.ActionContext context) (at Assets/CrashKonijn/GOAP/Demos/Complex/Actions/HaulItemAction.cs:44)
CrashKonijn.Goap.Behaviours.ActionBase`1[TActionData].Perform (CrashKonijn.Goap.Interfaces.IMonoAgent agent, CrashKonijn.Goap.Interfaces.IActionData data, CrashKonijn.Goap.Classes.ActionContext context) (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/ActionBase.cs:29)
CrashKonijn.Goap.Behaviours.AgentBehaviour.PerformAction () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs:155)
CrashKonijn.Goap.Behaviours.AgentBehaviour.RunMoveBeforePerforming () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs:104)
CrashKonijn.Goap.Behaviours.AgentBehaviour.Run () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/AgentBehaviour.cs:74)
CrashKonijn.Goap.Classes.Runners.GoapRunner.Run () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Classes/Runners/GoapRunner.cs:33)
CrashKonijn.Goap.Behaviours.GoapRunnerBehaviour.Update () (at Assets/CrashKonijn/GOAP/Runtime/CrashKonijn.Goap/Behaviours/GoapRunnerBehaviour.cs:46)

**Comment by crashkonijn** [comment]
Good morning!

I've had a look at it and I believe I've found the problem! I could not replicatie your start issues, but I do hope that's fixed as well. Could you let me know if this is the case?

Best way to test this, including demo scene fix, is to checkout this project and switch to the `fix/jobs-leaking-when-stopping` branch.

Thanks for you bug report!
