### ISSUE TITLE
Question: Why ComplexAgentBrain.class need handle the Goal?

### ISSUE THREAD

**Issue by a38782615** [crashkonijn/GOAP#66]
Why isn't this code written in the plan? Need to be dealt with separately?

        private void UpdateHunger()
        {
            if (this.hunger.hunger > 80)
            {
                this.agent.SetGoal<FixHungerGoal>(false);
                return;
            }

            if (this.agent.CurrentGoal is not FixHungerGoal)
                return;
            
            if (this.hunger.hunger < 20)
                this.DetermineGoal();
        }

        private void DetermineGoal()
        {
            switch (this.agentType)
            {
                case AgentType.Miner:
                    this.DetermineMinerGoals();
                    break;
                case AgentType.WoodCutter:
                    this.DetermineWoodCutterGoals();
                    break;
                case AgentType.Smith:
                    this.DetermineSmithGoals();
                    break;
                case AgentType.Cleaner:
                    this.DetermineCleanerGoals();
                    break;
            }
        }

**Comment by SiliconOrchid** [comment]
If you haven't already, I'd recommend following along with ["hollistic3d" goap tutorial course](https://www.youtube.com/watch?v=tdBWk2OVCWc&list=PLi-ukGVOag_1DCBZG1rRg_SpiyI6I5Qcr) over on the tubes.

In that tutorial series, I thought their suggestion to think about individual actions as *"being like domino-pieces that need to be assembled in a chain"* was helpful.   That completed chain represents the **sequence of actions needed to complete a particular goal**.

In this crashkonijn system,  the action planner serves that purpose of finding that best combination of domino-pieces.   That's a computationally expensive part, which IMO, this particular system addresses in a good way.

The **goal-planning system**, which is what you're asking about, genuinely **is a separate concern**

The goals provided in the demo are simplified - there's barely any goal-planning going on.    We are provided a hint of behavioural change - notably "hunger", which is used to reprioritise the choice of one goal over other activities.

It is likely that in your own game or prototype,  your implementation of goal-selection will be far more complex.

Something that I initially felt like it was missing from this framework, was that I thought that it **could be useful for the goal-planner to have access to the individual cost of each suitable action-tree**.  It seems like this could be a useful thing to influence which goal is chosen - for example,  choosing one goal over another, based on perhaps the cost needed to reach them;    However, if you think  through the implications of that, it would mean resolving the action-chain for each and every possible goals - all of the time (and not just resolving the action-chain of the currently selected goal).  That could be an **extremely expensive/wasteful thing to do**.

On an unrelated note, If you haven't already, I would recommend the [Crashkonijn Discord Channel](https://discord.gg/dCPnHaYNrm) as an alternative friendly place to ask for help and to have questions answered.

**Comment by crashkonijn** [comment]
Hi @a38782615!

To add to @SiliconOrchid explanation (thanks btw!);

GOAP does 2 things in essence:
1. Create a graph based on all the goals/actions connected based on their conditions and effects.
2. Resolve the next best action to perform to reach a chosen goal, based on that graph.

For certain games you might actually want Utility AI to determine what goal would be best, and let the GOAP perform a chain of tasks to reach that goal.

For other games, for example Rimworld, there might be a queue of available actions added by the player and the AI agent might choose one based on their skillset.

For simpler things you might use an FSM to determine the goal (like in the demo).

Determining what a proper goal is for an AI agent to perform is very game dependent, and as such is not provided by this package.

**Comment by crashkonijn** [comment]
I'm closing this issue since you reacted with a heart. If you have any more questions about this (or something else) don't hesitate to open a new ticket or post on our discord!
