### ISSUE TITLE
Feature: Disable actions (through code)

### ISSUE THREAD

**Issue by crashkonijn** [crashkonijn/GOAP#74]
**Is your feature request related to a problem? Please describe.**
When traversing the action graph to find a valid action to perform the resolver doesn't perform a 'full tree search' to see if ALL conditions could be met. Right now the system will just find any action that it can perform towards a goal, for any condition that isn't met in the tree.

There can be cases where a condition could be present in the world state, but where there's no action that could influence that particular world state.

Lets say you spawn an enemy with a random weapon which they cannot change. The `ShootBowAction` is not something that you'd like it to consider. You'd also not want it to `PickupArrows`. Adding a way to disable this action conditionally would solve this problem.

**Describe the solution you'd like**
I propose introducing a `public void IsEnabled(agent, references)` to an Action. By default it should return true.

**Comment by WillNichols726** [comment]
I'd also like to suggest this enhancement. I'm working on a turn-based game with a wide action space, and the ability to quickly eliminate actions that are not available to reduce the search space would be nice.

**Comment by crashkonijn** [comment]
Allright, I've added this to the v3 milestone :)

**Comment by crashkonijn** [comment]
Fixed for v3!
