### ISSUE TITLE
Bug: Cost of distance is not shown in the node viewer

### ISSUE THREAD

**Issue by crashkonijn** [crashkonijn/GOAP#88]
**Describe the bug**
When using the node viewer the cost of distance between nodes isn't shown.

**Screenshots**
![image](https://github.com/crashkonijn/GOAP/assets/5364802/2986841e-d603-42de-9418-90ee4eff4ab9)

**Comment by ravenmdt** [comment]
Looking forward to this functionality! Keep up the good work :)
